### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'hmmscan'

### ISSUE THREAD

**Issue by hxu105** [luost26/diffab#13]
Hello, I am trying to run the sample experiment for designing the six CDRs separately for the 7DK2_AB_C antibody-antigen complex. I am facing this issue, could you help me to look at it? Many thanks! <img width="801" alt="image" src="https://user-images.githubusercontent.com/40327643/213558090-16bf83cc-2f98-4c56-8d83-53116f98f054.png">

**Comment by hxu105** [comment]
Also encountering issues when run the training experiment. 
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/40327643/213577680-ae188532-1ac9-4fea-937f-bb2cd03338c5.png">

**Comment by luost26** [comment]
It seems that some packages are missing in your environment. Can you try
reinstalling your conda environment following the README
