### ISSUE TITLE
left-multiply or right-multiply ?

### ISSUE THREAD

**Issue by longlongman** [luost26/diffab#14]
According to the paper attachment, after sampling a random rotation $E \sim \mathcal{IG}_{SO(3)}(I, \sigma^2)$, we need to left-multiply $R$ to $E$ to get the desired random value $RE \sim \mathcal{IG}_SO(3)(R, \sigma^2)$. 

However, on the released code, 
https://github.com/luost26/diffab/blob/6febe0243c67c1e21e7b418ea38e0c25eca42f04/diffab/modules/diffusion/transition.py#L118
https://github.com/luost26/diffab/blob/6febe0243c67c1e21e7b418ea38e0c25eca42f04/diffab/modules/diffusion/transition.py#L134

$R$ is multiplied to $E$ from the right side.

Which operation is correct?

**Comment by luost26** [comment]
Both can add desired noise to the rotation matrix numerically.
If the base vectors of the residue are column vectors in R, then ER is more intuitive. Otherwise, RE is more intuitive.

**Comment by longlongman** [comment]
It is still confusing to me. I also take the column vectors as the base vectors. In this case, $RE$ is more intuitive to me (we first get $E$ around $I$ and transform it with $R$).

Moreover, $ER = (ERE^{-1})E \sim \mathcal{IG}_{SO(3)}(ERE^{-1}, \sigma^2)$, it seems that $RE$ and $ER$ do different things, because $ERE^{-1} = R$ is not always true.
