### ISSUE TITLE
missing streamlit dependency

### ISSUE THREAD

**Issue by awesome-crab** [luost26/diffab#18]
Hello,

I was wondering if you could add streamlit to the env yaml file.
This way streamlit is directly installed and the demo can be used.
Or else maybe provide an alternative installation maybe with pip?

I have a really hard time getting streamlit to run in a docker container together with diffab. the issue is that I cannot install streamlit with conda in a separate step.

Best regards,

**Comment by luost26** [comment]
Does appending a line `- streamlit` to `env.yml` work for you?

**Comment by luost26** [comment]
Added.

**Comment by awesome-crab** [comment]
Yes... Thanks for your quick action.
Unfortunately, when I try to create the conda environment conda takes forever to figure out the dependencies.
So I stopped it after hours of nothing happening.

I suggest you remove streamlit from the env.yml.

**Comment by awesome-crab** [comment]
When creating the conda env without streamlit and then activating the environment I am able to just pip install streamlit and stmol and it seems to work...

I feel really bad about pip installing inside the conda env... but to just have a look at the stremlit app it works
