### ISSUE TITLE
Why generating seqmap during data preprocessing?

### ISSUE THREAD

**Issue by smiles724** [luost26/diffab#8]
Hi, Luo,
Thanks for sharing the code.
I notice that you produce a key named 'seqmap' for each entity. However, this 'seqmap' seemed not to be used any longer. This is a very tine issue, and I just wonder the significance of this value.

**Comment by pengzhangzhi** [comment]
I am also curious. Did you find out why?

**Comment by smiles724** [comment]
> I am also curious. Did you find out why?

This seqmap is used to label CDRs.
